from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 597)
        MainWindow.setMinimumSize(QtCore.QSize(797, 597))
        MainWindow.setMaximumSize(QtCore.QSize(797, 597))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons8-youtube-squared-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(20, 20))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UrlInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UrlInput.setGeometry(QtCore.QRect(20, 10, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.UrlInput.setFont(font)
        self.UrlInput.setObjectName("UrlInput")
        self.VerifyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.VerifyBtn.setGeometry(QtCore.QRect(650, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.VerifyBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/icons8-link-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VerifyBtn.setIcon(icon1)
        self.VerifyBtn.setIconSize(QtCore.QSize(24, 24))
        self.VerifyBtn.setObjectName("VerifyBtn")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 761, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.Title = QtWidgets.QLabel(self.groupBox)
        self.Title.setGeometry(QtCore.QRect(40, 40, 701, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.Duration = QtWidgets.QLabel(self.groupBox)
        self.Duration.setGeometry(QtCore.QRect(40, 70, 701, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Duration.setFont(font)
        self.Duration.setObjectName("Duration")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 761, 261))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.NormalRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.NormalRadio.setGeometry(QtCore.QRect(70, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NormalRadio.setFont(font)
        self.NormalRadio.setChecked(True)
        self.NormalRadio.setEnabled(False)
        self.Title.setEnabled(False)
        self.Duration.setEnabled(False)
        self.NormalRadio.setObjectName("NormalRadio")
        self.VideoRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.VideoRadio.setGeometry(QtCore.QRect(340, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VideoRadio.setFont(font)
        self.VideoRadio.setChecked(False)
        self.VideoRadio.setObjectName("VideoRadio")
        self.AudioRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.AudioRadio.setGeometry(QtCore.QRect(610, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AudioRadio.setFont(font)
        self.AudioRadio.setObjectName("AudioRadio")
        self.NormalList = QtWidgets.QComboBox(self.groupBox_2)
        self.NormalList.setGeometry(QtCore.QRect(10, 80, 191, 22))
        self.NormalList.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NormalList.setFont(font)
        self.NormalList.setObjectName("NormalList")
        self.VideoList = QtWidgets.QComboBox(self.groupBox_2)
        self.VideoList.setEnabled(False)
        self.VideoList.setGeometry(QtCore.QRect(290, 80, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VideoList.setFont(font)
        self.VideoList.setObjectName("VideoList")
        self.AudioList = QtWidgets.QComboBox(self.groupBox_2)
        self.AudioList.setEnabled(False)
        self.AudioList.setGeometry(QtCore.QRect(560, 80, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AudioList.setFont(font)
        self.AudioList.setObjectName("AudioList")
        self.DestInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.DestInput.setEnabled(False)
        self.DestInput.setGeometry(QtCore.QRect(10, 150, 621, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.DestInput.setFont(font)
        self.DestInput.setObjectName("DestInput")
        self.FolderBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.FolderBtn.setEnabled(False)
        self.FolderBtn.setGeometry(QtCore.QRect(640, 150, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.FolderBtn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/icons8-file-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FolderBtn.setIcon(icon2)
        self.FolderBtn.setIconSize(QtCore.QSize(20, 20))
        self.FolderBtn.setObjectName("FolderBtn")
        self.DownloadBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.DownloadBtn.setEnabled(False)
        self.DownloadBtn.setGeometry(QtCore.QRect(310, 200, 141, 41))
        self.DownloadBtn.setMinimumSize(QtCore.QSize(141, 41))
        self.DownloadBtn.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.DownloadBtn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/icons8-download-26 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DownloadBtn.setIcon(icon3)
        self.DownloadBtn.setObjectName("DownloadBtn")
        self.ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ProgressBar.setEnabled(False)
        self.ProgressBar.setGeometry(QtCore.QRect(30, 510, 751, 23))
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setObjectName("ProgressBar")
        self.ProgressLabel = QtWidgets.QLabel(self.centralwidget)
        self.ProgressLabel.setEnabled(False)
        self.ProgressLabel.setGeometry(QtCore.QRect(30, 480, 701, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ProgressLabel.setFont(font)
        self.ProgressLabel.setObjectName("ProgressLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.VideoRadio.setEnabled(False)
        self.AudioRadio.setEnabled(False)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TubeDown"))
        self.UrlInput.setPlaceholderText(_translate("MainWindow", "Enter a valid youtube url or video ID"))
        self.VerifyBtn.setText(_translate("MainWindow", "Verify"))
        self.groupBox.setTitle(_translate("MainWindow", "Video details"))
        self.Title.setText(_translate("MainWindow", "Video title : None"))
        self.Duration.setText(_translate("MainWindow", "Duration :None"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Download options"))
        self.NormalRadio.setText(_translate("MainWindow", "Normal"))
        self.VideoRadio.setText(_translate("MainWindow", "Video Only"))
        self.AudioRadio.setText(_translate("MainWindow", "Audio Only"))
        self.DestInput.setPlaceholderText(_translate("MainWindow", "Select a destination"))
        self.FolderBtn.setText(_translate("MainWindow", "Select folder"))
        self.DownloadBtn.setText(_translate("MainWindow", "Download"))
        self.ProgressLabel.setText(_translate("MainWindow", "Download progress"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
